# Generated by Django 3.0.5 on 2020-04-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200409_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
