# Generated by Django 3.0.5 on 2020-04-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200410_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
