# Generated by Django 3.0.5 on 2020-04-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200414_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
