# Generated by Django 3.0.5 on 2020-04-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_auto_20200410_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('like', models.IntegerField(null=True, verbose_name='likes')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commant_author', to='account.User')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=300, verbose_name='image')),
                ('content', models.TextField(verbose_name='content')),
                ('like', models.IntegerField(null=True, verbose_name='likes')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feeds',
            },
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_id', to='feed.Comment')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_id', to='feed.Feed')),
            ],
            options={
                'db_table': 'feed_comment',
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='comment',
            field=models.ManyToManyField(related_name='feed_comment', through='feed.FeedComment', to='feed.Comment'),
        ),
        migrations.AddField(
            model_name='feed',
            name='feed',
            field=models.ManyToManyField(related_name='comment_feed', through='feed.FeedComment', to='feed.Feed'),
        ),
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='account.User'),
        ),
        migrations.AddField(
            model_name='feed',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar', to='account.UserProfile'),
        ),
    ]
